export const dataCarouselHomePage = [
  {
    id: 1,
    title: "Mario Kart™ 8 Deluxe",
    price: "$59.99",
    category: "Nintendo Switch",
    linkImg: "",
  },
  {
    id: 2,
    title: "TRIANGLE STRATEGY™",
    price: "$59.99",
    category: "Nintendo Switch",
    linkImg: "",
  },
  {
    id: 3,
    title: "Pokémon™ Legends: Arceus",
    price: "$59.99",
    category: "Nintendo Switch",
    linkImg: "",
  },
  {
    id: 4,
    title: "Super Mario™ 3D World + Bowser’s Fury",
    price: "$59.99",
    category: "Nintendo Switch",
    linkImg: "",
  },
  {
    id: 5,
    title: "Cuphead",
    price: "$19.99",
    category: "Nintendo Switch",
    linkImg: "",
  },
  {
    id: 6,
    title: "Minecraft",
    price: "$29.99",
    category: "Nintendo Switch",
    linkImg: "",
  },
  {
    id: 7,
    title: "Mario + Rabbids® Kingdom Battle",
    price: "$59.99",
    category: "Nintendo Switch",
    linkImg: "",
  },
  {
    id: 8,
    title: "Unravel Two",
    price: "$59.99",
    category: "Nintendo Switch",
    sale: 63,
    linkImg: "",
  },
  {
    id: 9,
    title: "Unravel Two",
    price: "$59.99",
    category: "Nintendo Switch",
    sale: 63,
    linkImg: "",
  },
  {
    id: 10,
    title: "Unravel Two",
    price: "$59.99",
    category: "Nintendo Switch",
    sale: 63,
    linkImg: "",
  },
];
